
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Toolbar from "@/component/Navigation/Toolbar";
import Footersection from "@/component/Footer/Footersection";
import { Poppins } from 'next/font/google';
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ['latin'],
   weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toolbar />
        {children}
        <Footersection />
      </body>
    </html>
  );
}
